# Generated by Django 3.1.5 on 2021-02-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='energy_supplier',
            field=models.CharField(choices=[('BS', 'bog standard'), ('GT', 'a great green tarif')], default='BS', max_length=2),
        ),
        migrations.AddField(
            model_name='pledge',
            name='heating_source',
            field=models.CharField(choices=[('GO', 'gas or oil'), ('EL', 'electricity')], default='GO', max_length=2),
        ),
    ]
